# Generated by Django 4.0.4 on 2022-07-08 06:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=250)),
                ('dep_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dist_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=250)),
                ('Dist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=250)),
                ('doc_spec', models.TextField()),
                ('doc_img', models.ImageField(upload_to='doc_img')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('phn', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='other', max_length=10)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('b+', 'B+'), ('a-', 'A-'), ('b-', 'B-'), ('ab-', 'AB-'), ('ab+', 'AB+'), ('o+', 'O+'), ('o-', 'O-')], default='other', max_length=10)),
                ('address', models.TextField()),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.departments')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.district')),
                ('doctor', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='department', chained_model_field='dep_name', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.doctors')),
                ('sub_branch', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='district', chained_model_field='Dist_name', on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.subbranches')),
            ],
        ),
    ]
